# Google Gemini Image Library Agent
#
# Author: Peter Jakubowski
# Date: 2/1/2025
# Description: Database schema
#

from pydantic.dataclasses import dataclass as pydantic_dataclass
from pydantic import BaseModel, RootModel, Field, ConfigDict
from datetime import datetime

# =========================
# ==== Database Schema ====
# =========================


# Core schema
@pydantic_dataclass
class Assets:
    """
    The root table of our database keeps track of the assets in our system.

    """

    # Configure the BaseModel to ignore any extra attributes given at creation
    model_config = ConfigDict(extra='ignore')
    id: int = Field(default=None)
    image_path: str = Field(default=None)
    file_name: str | None = Field(default=None)
    file_type: str | None = Field(default=None)


# Metadata schema
@pydantic_dataclass
class AssetMetadata:
    """
    The metadata table in our database keeps record of select image metadata that is extracted from the original image.
    For simplicity, we're going to save our list of keywords as a comma separated string.

    """

    # Configure the BaseModel to ignore any extra attributes given at creation
    model_config = ConfigDict(extra='ignore')
    id: int = Field(default=None)
    capture_date: datetime | None = Field(default=None)
    description: str | None = Field(default=None)
    keywords: str | None = Field(default=None)
    creator: str | None = Field(default=None)
    person_in_image: str | None = Field(default=None)
    location: str | None = Field(default=None)
    city: str | None = Field(default=None)
    state: str | None = Field(default=None)


# Generative schema
@pydantic_dataclass
class GenerativeMetadata:
    """
    The generative table in our database keeps record of generated content created by the Gemini model.
    For simplicity, we're going to save our list of keywords as a comma separated string.

    """

    # Configure the BaseModel to ignore any extra attributes given at creation
    model_config = ConfigDict(extra='ignore')
    id: int = Field(default=None)
    description: str = Field(default=None)
    keywords: str = Field(default=None)
    style: str = Field(default=None)
    mood: str = Field(default=None)


# Embedding schema
@pydantic_dataclass
class Embeddings:
    """
    The embedding table in our database keeps record of embeddings generated by the Gemini model.

    """

    # Configure the BaseModel to ignore any extra attributes given at creation
    model_config = ConfigDict(extra='ignore')
    id: int = Field(default=None)
    genai_description_vector: bytes = Field(default=None)

# =========================
# ==== Response Schema ====
# =========================


# Generative description model response schema
class DescriptionResponseSchema(BaseModel):
    description: str  # Long description of the image
    keywords: list[str]  # List of keywords describing the image
    style: str  # The style of the image
    mood: str  # The mood of the image
